### ISSUE TITLE
Zonefiles for .br

### ISSUE THREAD

**Issue by MatheusAvellar** [jschauma/tld-zoneinfo#1]
Hey, Jan! After reading your blog post on TLDs back in August 2021, I contacted `.br`'s registry, [Registro.br](https://en.wikipedia.org/wiki/Registro.br), inquiring about `.br`'s zonefiles. Unfortunately (and expectedly), it's not publicly available.

Here's the response in full (translated by myself):

> From: Hostmaster Registro .br <hostmaster@registro.br>
> Date: Thu, Aug 19, 2021 at 3:41 PM
> Subject: Re: [BR-2021081919.614] Zonefiles for .br
> To: Matheus Avellar <xxxxx@xxxx>
>
> Dear Mr. Matheus, good afternoon.
> 
> The information you desire is not made publicly available. Any information in that regard is found in the following link:
> 
> https://registro.br/dominio/estatisticas/
> 
> Sincerely,
> Giovani de Freitas

Now, I didn't open a PR for this, since I'm not sure you'll want this added to the README. However, since you did add a statistics link for Czech Republic's TLD, I thought it would be worth letting you know `.br` has a similar page.

Parallel to that, I have also been on and off (mostly off) hunting for all second-level domains registered directly under `.br`. I have managed to find 803 (~66.5%) out of a total 1207 the statistics page claims are registered. The list is made available here: https://lab.avl.la/.br/

The list is currently not in any standardized form – I'm not too familiar with AXFR, or DNS and Zonefiles in general to be honest – and I intend on fixing that eventually. Currently, it's a CSV where:

- If a domain has A, AAAA or CNAME records, their values will be listed (e.g. `eb.br` had an A record of `200.20.120.33`);
- If the corresponding www subdomain has A, AAAA or CNAME records, their values will be listed (e.g. `on.br` had an A record of `200.20.187.134` for both its root and its www subdomain);
- Otherwise, if there's any other DNS records (usually for domains intended as subdomains only, like `com.br`), they'll be listed (e.g. `b.br`'s entry on the list has `"NS, SOA, RRSIG"` under the "other DNS records" column).

Hopefully it's useful to you in some way!

Cheers

**Comment by jschauma** [comment]
Nice, thanks for reporting!  Added a link to the README.
