### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by JacksonChen666** [jschauma/tld-zoneinfo#2]
This project does not seem to have a license declared in an obvious way, or at all. A license should be added (as this project seems to be intended as open source) so that users can run, modify, study, distribute, and use [the code](https://github.com/jschauma/tld-zoneinfo/blob/main/tools/fetch-fi.sh) (and maybe also [the README.md](https://github.com/jschauma/tld-zoneinfo/blob/main/README.md)).

https://choosealicense.com/no-permission/

**Comment by jschauma** [comment]
I explicitly placed everything here into the public domain. Hope that helps.
